FROM ubuntu:24.04

# Install dependencies
RUN apt-get update && \
    apt-get -y install curl ca-certificates gnupg2 build-essential dos2unix --no-install-recommends && \
    apt-get clean

# Instructions from https://rvm.io/rvm/install
RUN curl -sSL https://rvm.io/mpapis.asc | gpg --import -
RUN curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
RUN curl -sSL https://get.rvm.io | bash -s stable
RUN /bin/bash -c '. /etc/profile.d/rvm.sh && rvm install 3.1.7 && gem install bundler'

WORKDIR /tmp/workspace

# Install Ruby dependencies
COPY Gemfile Gemfile.lock ./
RUN /bin/bash -c '. /etc/profile.d/rvm.sh && bundle'

# Copy scripts code and tests.
COPY jobs/ ./jobs/
COPY spec/ ./spec/

# Traverse through the directory and force line endings to Unix.
RUN find jobs/ spec/jobs/ -type f -name '*' | xargs dos2unix

# Override /bin/systemctl - the Docker container doesn't start under Systemd, so calls to systemctl fail.
# We don't really need systemctl, so this is enough as a workaround.
RUN printf '#!/bin/sh\nexit 0\n' > /bin/systemctl && chmod +x /bin/systemctl

ENTRYPOINT /bin/bash -c '. /etc/profile.d/rvm.sh && bundle exec rspec --tag linux --format documentation'
