version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run integration tests on Ubuntu 24.04 and Ubuntu 26.04 containers
          command: ./integration/linux/run-tests.sh
