version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run integration tests on Ubuntu 14.04 and Ubuntu 16.04 containers
          command: ./scripts/integration-tests.sh
