FROM mcr.microsoft.com/windows/servercore:ltsc2019

# Install Chocolatey.
RUN powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

# Install Ruby
RUN choco install ruby -y

WORKDIR c:/workspace

# Install Ruby dependencies
COPY Gemfile ./
RUN bundle

# Copy scripts code and tests.
COPY jobs/ ./jobs/
COPY spec/ ./spec/

ENTRYPOINT bundle exec rspec --tag windows --format documentation
